language: cpp
compiler: gcc
os: 
  - osx
  - linux

before_install:
  - echo $TRAVIS_OS_NAME
  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi

install:
  - echo $TRAVIS_OS_NAME
  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libglu1-mesa-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install xorg-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libasound2-dev; fi
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cmake; fi

script:
  - echo $TRAVIS_OS_NAME

  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips set config linux-make-unittest; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips clean all; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips build; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips make test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips build linux-make-profiling; fi

  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips set config oryol-osx-unittest-headless; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips clean all; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips make ALL_BUILD; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips make RUN_TESTS; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips build osx-make-profiling; fi

