# https://ci.appveyor.com/project/floooh/oryol
---
branches:
    except:
        - gh-pages

clone_depth: 3 

# just perform builds for now, don't run tests
build_script:
    - cmd: python fips build win64-vstudio-debug
    - cmd: python fips build d3d11-win64-vstudio-debug

